#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# display "bad luck" insted of 4
# display "good luck" instead of 8

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"

    elif [ $counter -eq 8 ]; then
        echo "good luck"

    else
        echo "Best School"
    fi
    ((counter++))
done
