#!/usr/bin/env bash
# diplay numbers fom 1 to 20
# display "bad luck from China" at 4th loop iteration
# display "bad luck from Japan" at 9th loop iteration
# display "bad luck from Italy" at 17th loop iteration

counter=1

while [ $counter -le 20 ]; do
    echo "$counter"
    if [ $counter -eq 4 ]; then
        echo "bad luck from China"
    elif [ $counter -eq 9 ]; then
        echo "bad luck from Japan"
    elif [ $counter -eq 17 ]; then
        echo "bad luck from Italy"
    fi
    ((counter++))
done
