#!/usr/bin/env bash
# script that give you information about school file

file="school"
if test -e "$file"; then
    echo "school file exist"
    if test ! -s "$file"; then
        echo "school file is empty"
        if test -f "$file"; then
            echo "school is a regular file"
        fi
    elif test -s "$file"; then
        echo "school file is not empty"
        if test -f "$file"; then
            echo "school is a regular file"
        fi
    fi
else
    echo "school file does not exist"
fi
